/* eslint-disable react/jsx-key */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeShopListJson from "../data/coffee-stores.json";

// We are using the getStaticPropis function so we pre-render the content (pre-content generation) ------------ getStaticProps is the function
export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeShopListJson,
      // if we declared coffeeStores: coffeeStores, we could also write just as 'coffeeStores', since the key and the value is the same
    }, // will be passed to the page component as props
  }
}
// end of We are using the getStaticPropis function so we pre-render the content (pre-content generation) ------------ getStaticProps is the function

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Conoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt=""
            layout='fill'
          />
        </div>
        {/* This is some sort of if statement I've never seen before, but it essentially says if there are stores (length > 0), render this section */}
        
        {props.coffeeStores.length > 0 && (
            <>
              <h2 className={styles.heading2}>Toronto Stores</h2>
              <div className={styles.cardLayout}>
                {props.coffeeStores.map((coffeeStore) => {
                      return (
                        <Card
                          key={coffeeStore.id}
                          name={coffeeStore.name}
                          imgUrl={coffeeStore.imgUrl}
                          href={`/coffee-store/${coffeeStore.id}`}
                        />
                      )
                    }
                  )
                }
              </div>
            </>
          )
        }
      </main>
    </div>
  )
}
