/* eslint-disable react/jsx-key */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeShopListJson from "../data/coffee-stores.json";

// We are putting in this function so we pre-render the content (pre-content generation) ------------ getStaticProps is the function
export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeShopListJson,
      // if we declared coffeeStores: coffeeStores, we could also write just as 'coffeeStores', since the key and the value is the same
    }, // will be passed to the page component as props
  }
}
// end of We are putting in this function so we pre-render the content (pre-content generation)

export default function Home(props) {
  console.log("props", props)
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Conoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt=""
            layout='fill'
          />
        </div>
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/coffee-store/${coffeeStore.id}`}
                  />
                )
              }
            )
          }
        </div>
      </main>
    </div>
  )
}
